### ISSUE TITLE
How to print a preview

### ISSUE THREAD

**Issue by FreeVB** [russjudge/Simple-WPF-Report-Printer#1]
How to print a preview?

**Comment by russjudge** [comment]
As a tool for providing a quick and simple function, a print preview function is not available, and such functionality is out-of-scope for its intended purpose and will therefore not be developed at this time.  Such functionality would require a major redesign of the entire project.  This project depends on the behavior of System.Windows.Controls.PrintDialog for printing.  PrintDialog has no PrintPreview functionality, so to provide PrintPreview, this project would need to be completely rebuilt using a different mechanism.
